export var HTTP_STATUS;
(function (HTTP_STATUS) {
    HTTP_STATUS[HTTP_STATUS["OK"] = 200] = "OK";
    HTTP_STATUS[HTTP_STATUS["CREATED"] = 201] = "CREATED";
    HTTP_STATUS[HTTP_STATUS["BAD_REQUEST"] = 400] = "BAD_REQUEST";
    HTTP_STATUS[HTTP_STATUS["UNAUTHORIZED"] = 401] = "UNAUTHORIZED";
    HTTP_STATUS[HTTP_STATUS["FORBIDDEN"] = 403] = "FORBIDDEN";
    HTTP_STATUS[HTTP_STATUS["NOT_FOUND"] = 404] = "NOT_FOUND";
    HTTP_STATUS[HTTP_STATUS["CONFLICT"] = 409] = "CONFLICT";
    HTTP_STATUS[HTTP_STATUS["INTERNAL_SERVER_ERROR"] = 500] = "INTERNAL_SERVER_ERROR";
})(HTTP_STATUS || (HTTP_STATUS = {}));
export const RESPONSE_MESSAGE = {
    [HTTP_STATUS.BAD_REQUEST]: '요청 형식이 올바르지 않습니다.',
    [HTTP_STATUS.UNAUTHORIZED]: '로그인이 필요합니다.',
    [HTTP_STATUS.FORBIDDEN]: '권한이 없습니다.',
    [HTTP_STATUS.NOT_FOUND]: '리소스를 찾을 수 없습니다.',
    [HTTP_STATUS.CONFLICT]: '요청 충돌이 발생했습니다.',
    [HTTP_STATUS.INTERNAL_SERVER_ERROR]: '서버 오류가 발생했습니다.',
};
